# -*- coding: utf-8 -*-


# This file was *autogenerated* from the file solver.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_48 = Integer(48); _sage_const_3 = Integer(3); _sage_const_1337 = Integer(1337); _sage_const_3000 = Integer(3000); _sage_const_5 = Integer(5); _sage_const_20000 = Integer(20000); _sage_const_256 = Integer(256); _sage_const_255 = Integer(255)#!/usr/bin/env sage

import json
import sys
import time
import itertools
import numpy as np

try:                      # chay trong Sage
    GF
    USE_SAGE = True
except NameError:         # chay bang python thuong (de test)
    USE_SAGE = False

I0 = int(_sage_const_0 )
I1 = int(_sage_const_1 )
I2 = int(_sage_const_2 )

def np_rref(M, p):
    A = np.array(M, dtype=np.int64) % p
    rows, cols = A.shape
    piv = []
    r = I0
    for c in range(cols):
        if r >= rows:
            break
        nz = np.nonzero(A[r:, c])[I0]
        if len(nz) == I0:
            continue
        k = r + int(nz[I0])
        if k != r:
            A[[r, k]] = A[[k, r]]
        A[r] = A[r] * pow(int(A[r, c]), -I1, p) % p
        f = A[:, c].copy()
        f[r] = I0
        A = (A - f[:, None] * A[r][None, :]) % p
        piv.append(c)
        r += I1
    return A, piv


def to_np(Msage):
    return np.array([[int(v) for v in row] for row in Msage.rows()], dtype=np.int64)


def pivots_of(M, p):
    """chi so cot pivot cua rref(M)"""
    if USE_SAGE:
        return [int(c) for c in matrix(GF(p), M.tolist()).pivots()]
    return np_rref(M, p)[I1]


def row_basis(M, p):
    """co so (theo hang) cua khong gian hang"""
    if USE_SAGE:
        B = matrix(GF(p), M.tolist()).row_space().basis_matrix()
        return to_np(B).reshape(-I1, M.shape[I1])
    R, piv = np_rref(M, p)
    return R[:len(piv)]


def right_kernel(M, p):
    """cac vector v (theo hang) sao cho M v = 0"""
    if USE_SAGE:
        K = matrix(GF(p), M.tolist()).right_kernel().basis_matrix()
        return to_np(K).reshape(-I1, M.shape[I1])
    R, piv = np_rref(M, p)
    cols = M.shape[I1]
    free = [c for c in range(cols) if c not in piv]
    out = np.zeros((len(free), cols), dtype=np.int64)
    for a, f in enumerate(free):
        out[a, f] = I1
        for i, c in enumerate(piv):
            out[a, c] = (-R[i, f]) % p
    return out


def left_kernel(M, p):
    return right_kernel(np.ascontiguousarray(M.T), p)


def mat_inv(M, p):
    if USE_SAGE:
        return to_np(matrix(GF(p), M.tolist()).inverse())
    k = M.shape[I0]
    R, piv = np_rref(np.hstack([M % p, np.eye(k, dtype=np.int64)]), p)
    assert piv[:k] == list(range(k)), "ma tran suy bien"
    return R[:, k:]


def complement_unit(M, dim, p):
    """cac vector don vi e_i bo sung cho khong gian hang cua M thanh toan khong gian"""
    piv = set(pivots_of(M, p))
    return [i for i in range(dim) if i not in piv]


path = sys.argv[I1] if len(sys.argv) > I1 else "out.txt"
t0 = time.time()
data = json.load(open(path))
pk = data["public_key"]
par = pk["parameters"]
p, n, m, t, s = (int(par[k]) for k in ("p", "n", "m", "t", "s"))
tail = n - t            # 16  (bien vinegar + oil)
oil = n - t - s         # 12
nU = m - t              # 18
INV2 = (p + I1) // I2
blocks = data["ciphertext"]["blocks"]
print("[*] p=%d n=%d m=%d t=%d s=%d | %d block ban ma" % (p, n, m, t, s, len(blocks)))

mon_index = {}
for poly in pk["polynomials"]:
    for c, mon in poly:
        key = tuple(mon)
        if key not in mon_index:
            mon_index[key] = len(mon_index)
N = len(mon_index)
mons = [None] * N
for k, v in mon_index.items():
    mons[v] = k
C = np.zeros((m, N), dtype=np.int64)
for i, poly in enumerate(pk["polynomials"]):
    for c, mon in poly:
        C[i, mon_index[tuple(mon)]] = c
deg = np.array([len(k) for k in mons])
IDX = np.full((N, _sage_const_4 ), n, dtype=np.int64)          # n = chi so cua hang so 1
for j, k in enumerate(mons):
    for d, v in enumerate(k):
        IDX[j, d] = v
Cf = C.astype(np.float64)
print("[*] %d don thuc, doc xong sau %.1fs" % (N, time.time() - t0))


def evalP(X):
    """X: (n, npts) -> (m, npts), gia tri 34 da thuc cong khai"""
    X = X % p
    out = []
    for s0 in range(I0, X.shape[I1], _sage_const_48 ):
        Xc = X[:, s0:s0 + _sage_const_48 ]
        Xe = np.vstack([Xc, np.ones((I1, Xc.shape[I1]), dtype=np.int64)])
        Mv = Xe[IDX[:, _sage_const_0 ]] * Xe[IDX[:, _sage_const_1 ]] * Xe[IDX[:, _sage_const_2 ]] * Xe[IDX[:, _sage_const_3 ]]
        Mv = (Mv % p).astype(np.float64)
        out.append((np.rint(Cf @ Mv).astype(np.int64)) % p)
    return np.hstack(out)


high = np.nonzero(deg >= _sage_const_3 )[I0]
rng = np.random.default_rng(int(_sage_const_1337 ))
sub = rng.choice(high, size=_sage_const_3000 , replace=False)
Lam = left_kernel(C[:, sub], p)                      # (16, 34)
assert Lam.shape[I0] == t, "so chieu khong gian w = %d (mong doi %d)" % (Lam.shape[I0], t)
assert not ((Lam @ C[:, high]) % p).any(), "kernel khong triet tieu toan bo bac cao"
G = (Lam @ C) % p                                    # 16 da thuc bac <= 2
print("[*] Buoc 1: tim duoc %d to hop bac <= 2" % Lam.shape[I0])

c0 = G[:, mon_index[()]].copy()
lin = np.zeros((t, n), dtype=np.int64)
for i in range(n):
    lin[:, i] = G[:, mon_index[(i,)]]
S3 = np.zeros((t, n, n), dtype=np.int64)
for key, col in mon_index.items():
    if len(key) == I2:
        i, j = key
        if i == j:
            S3[:, i, i] = (I2 * G[:, col]) % p
        else:
            S3[:, i, j] = G[:, col]
            S3[:, j, i] = G[:, col]

R = right_kernel(S3.reshape(t * n, n), p)            # (dim, n)
assert R.shape[I0] == tail - I0 + I0 and R.shape[I0] == n - tail, "radical co so chieu %d" % R.shape[I0]
Bh = R.T.copy()                                       # (n, 16)
comp = complement_unit(Bh.T, n, p)
Bu = np.zeros((n, len(comp)), dtype=np.int64)
for k, i in enumerate(comp):
    Bu[i, k] = I1
Lh = (lin @ Bh) % p
Lh_inv = mat_inv(Lh, p)
print("[*] Buoc 2: radical dim=%d, Lh kha nghich" % R.shape[I0])


def xmap(U, v):
    """U: (16, npts) toa do u ; v: (16,) gia tri lambda.P = lambda.ct  -> x (n, npts)"""
    X0 = (Bu @ U) % p
    SX = np.einsum("jab,bp->jap", S3, X0)
    quad = (X0[None] * SX).sum(axis=I1) % p
    g = (c0[:, None] + lin @ X0 + INV2 * quad) % p
    h = (Lh_inv @ ((v[:, None] - g) % p)) % p
    return (X0 + Bh @ h) % p


# nhom 18 vector bo sung de Lam + Nmat = co so cua F_p^34
compN = complement_unit(Lam, m, p)
assert len(compN) == nU
Nmat = np.zeros((nU, m), dtype=np.int64)
for k, i in enumerate(compN):
    Nmat[k, i] = I1

ct0 = np.array(blocks[I0], dtype=np.int64)
v0 = (Lam @ ct0) % p
pts = [np.zeros(tail, dtype=np.int64)]
E = np.eye(tail, dtype=np.int64)
for i in range(tail):
    pts.append(E[i])
for i in range(tail):
    pts.append((-E[i]) % p)
pair_index = {}
for i in range(tail):
    for j in range(i + I1, tail):
        pair_index[(i, j)] = len(pts)
        pts.append((E[i] + E[j]) % p)
Up = np.array(pts).T                                  # (16, 153)
Yp = (Nmat @ evalP(xmap(Up, v0))) % p                 # (18, 153)
f0 = Yp[:, I0]
fp = Yp[:, I1:I1 + tail]
fm = Yp[:, I1 + tail:I1 + I2 * tail]
H = np.zeros((nU, tail, tail), dtype=np.int64)
for i in range(tail):
    H[:, i, i] = (fp[:, i] + fm[:, i] - I2 * f0) % p
for (i, j), col in pair_index.items():
    H[:, i, j] = (Yp[:, col] - fp[:, i] - fp[:, j] + f0) % p
    H[:, j, i] = H[:, i, j]
# kiem tra tinh bac 2 chinh xac cua ham tren lat cat
for _ in range(_sage_const_5 ):
    u = rng.integers(_sage_const_0 , p, size=tail)
    pred = (f0 + ((fp - fm) * INV2 % p) @ u + INV2 * np.einsum("a,vab,b->v", u, H, u)) % p
    real = (Nmat @ evalP(xmap(u[:, None], v0)))[:, I0] % p
    assert (pred == real).all(), "ham tren lat cat khong phai bac 2"
print("[*] Buoc 3: ham tren lat cat dung la da thuc bac 2 theo u")

kers = []
for _ in range(I2):
    r = rng.integers(_sage_const_1 , p, size=nU)
    Hr = np.tensordot(r, H, axes=(I0, I0)) % p
    K = right_kernel(Hr, p)
    assert K.shape[I0] == oil - s, "dim ker = %d (mong doi %d)" % (K.shape[I0], oil - s)
    kers.append(K)
Ob = row_basis(np.vstack(kers), p)                    # (12, 16)
assert Ob.shape[I0] == oil, "dim O = %d" % Ob.shape[I0]
Ob = Ob.T.copy()                                      # (16, 12)
for k in range(nU):
    assert not ((Ob.T @ H[k] @ Ob) % p).any()
compV = complement_unit(Ob.T, tail, p)
Vb = np.zeros((tail, len(compV)), dtype=np.int64)
for k, i in enumerate(compV):
    Vb[i, k] = I1
assert Vb.shape[I1] == s
print("[*] Tim duoc khong gian oil O (dim %d), thoi gian %.1fs" % (oil, time.time() - t0))

INVT = np.zeros(p, dtype=np.int64)
for a in range(I1, p):
    INVT[a] = pow(a, -I1, p)
AA = np.array(list(itertools.product(range(p), repeat=s)), dtype=np.int64)   # (p^s, s)


def solve_block(ct):
    ct = np.array(ct, dtype=np.int64)
    v = (Lam @ ct) % p
    tgt = (Nmat @ ct) % p
    # cac diem (a, b) can danh gia
    P = []                                  # (a, b)
    za, zb = np.zeros(s, dtype=np.int64), np.zeros(oil, dtype=np.int64)
    Ea, Eb = np.eye(s, dtype=np.int64), np.eye(oil, dtype=np.int64)
    P.append((za, zb))
    for i in range(s):
        P.append((Ea[i], zb))
    for i in range(s):
        P.append(((-Ea[i]) % p, zb))
    ij = {}
    for i in range(s):
        for j in range(i + I1, s):
            ij[(i, j)] = len(P)
            P.append(((Ea[i] + Ea[j]) % p, zb))
    kk = {}
    for k in range(oil):
        kk[(-I1, k)] = len(P)
        P.append((za, Eb[k]))
    for i in range(s):
        for k in range(oil):
            kk[(i, k)] = len(P)
            P.append((Ea[i], Eb[k]))
    Upts = np.array([(Vb @ a + Ob @ b) % p for a, b in P]).T
    Y = (Nmat @ evalP(xmap(Upts, v)) - tgt[:, None]) % p            # (18, npts)
    F0 = Y[:, I0]
    ci = (Y[:, I1:I1 + s] - Y[:, I1 + s:I1 + I2 * s]) * INV2 % p
    cii = (Y[:, I1:I1 + s] + Y[:, I1 + s:I1 + I2 * s] - I2 * F0[:, None]) * INV2 % p
    cij = {key: (Y[:, c] - Y[:, I1 + key[I0]] - Y[:, I1 + key[I1]] + F0) % p for key, c in ij.items()}
    D0 = np.stack([(Y[:, kk[(-I1, k)]] - F0) % p for k in range(oil)], axis=I1)     # (18, 12)
    Di = np.zeros((s, nU, oil), dtype=np.int64)
    for i in range(s):
        for k in range(oil):
            Di[i, :, k] = (Y[:, kk[(i, k)]] - Y[:, I1 + i] - D0[:, k]) % p
    found = []
    CH = _sage_const_20000 
    for st in range(I0, AA.shape[I0], CH):
        A = AA[st:st + CH]
        B = A.shape[I0]
        cvec = np.tile(F0, (B, I1)).astype(np.int64)
        for i in range(s):
            cvec = cvec + A[:, i:i + I1] * ci[:, i][None, :] + (A[:, i:i + I1] ** I2) * cii[:, i][None, :]
        for (i, j), val in cij.items():
            cvec = cvec + (A[:, i] * A[:, j])[:, None] * val[None, :]
        cvec %= p
        M = np.zeros((B, nU, oil + I1), dtype=np.int32)
        M[:, :, :oil] = D0[None]
        for i in range(s):
            M[:, :, :oil] += (A[:, i][:, None, None] * Di[i][None]).astype(np.int32)
        M[:, :, oil] = (-cvec) % p
        M %= p
        ar = np.arange(B)
        alive = np.ones(B, dtype=bool)
        for col in range(oil):
            nzm = M[:, col:, col] != I0
            alive &= nzm.any(axis=I1)
            piv = col + nzm.argmax(axis=I1)
            rc = M[ar, col, :].copy()
            rp = M[ar, piv, :].copy()
            M[ar, col, :] = rp
            M[ar, piv, :] = rc
            inv = INVT[M[:, col, col]].astype(np.int32)
            M[:, col, :] = (M[:, col, :] * inv[:, None]) % p
            fac = M[:, :, col].copy()
            fac[:, col] = I0
            M = (M - fac[:, :, None] * M[:, col:col + I1, :]) % p
        ok = alive & (M[:, oil:, oil] == I0).all(axis=I1)
        for q in np.nonzero(ok)[I0]:
            a = A[q]
            b = M[q, :oil, oil].astype(np.int64)
            found.append((a, b))
    sols = []
    for a, b in found:
        u = ((Vb @ a + Ob @ b) % p)[:, None]
        x = xmap(u, v)
        if ((evalP(x)[:, I0] - ct) % p == I0).all():
            sols.append([int(z) for z in x[:, I0]])
    return sols


def byte_width(p):
    w = I1
    while p ** w < _sage_const_256 :
        w += I1
    return w


def decode_frame(digits, p, n):
    width = byte_width(p)
    if len(digits) < _sage_const_4  * width:
        raise ValueError("thieu header")

    def decode_byte(start):
        value = I0
        for d in digits[start:start + width]:
            value = value * p + d
        if value > _sage_const_255 :
            raise ValueError("khong phai byte")
        return value

    length = int.from_bytes(bytes(decode_byte(i * width) for i in range(_sage_const_4 )), "big")
    end = (_sage_const_4  + length) * width
    if end > len(digits) or len(digits) != ((end + n - _sage_const_1 ) // n) * n or any(digits[end:]):
        raise ValueError("do dai/padding sai")
    return bytes(decode_byte(i) for i in range(_sage_const_4  * width, end, width))


all_sols = []
for bi, ct in enumerate(blocks):
    t1 = time.time()
    sols = solve_block(ct)
    print("[*] Block %d: %d nghiem (%.1fs)" % (bi, len(sols), time.time() - t1))
    if not sols:
        sys.exit("khong tim thay nghiem cho block %d" % bi)
    all_sols.append(sols)

for combo in itertools.product(*all_sols):
    digits = [d for blk in combo for d in blk]
    try:
        pt = decode_frame(digits, p, n)
    except ValueError:
        continue
    print("[+] FLAG:", pt.decode("utf-8", "replace"))
    break
else:
    print("[-] khong giai ma duoc khung nao hop le")

